apiVersion: v1
kind: Service
metadata:
  name: kibana-logging
  namespace: kube-system
  labels:
    k8s-app: kibana-logging
    kubernetes.io/name: "Kibana"
spec:
  type: LoadBalancer
  ports:
  - name: http
    protocol: TCP
    port: 5601
    targetPort: 5601
  selector:
    k8s-app: kibana-logging
